//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBrowserF4
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShow
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ShowId { get; set; }
        public Nullable<decimal> Bookmark { get; set; }
    
        public virtual Show Show { get; set; }
        public virtual User User { get; set; }
    }
}
